apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sorn-hipsweep-storage
  namespace: hengenlab
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 100Gi
